export const USER_LOGIN = 'USER_LOGIN';

export const LOGIN_FAIL = 'LOGIN_FAIL';

export const SET_CHOSEN_CONTACT_ID = 'SET_CHOSEN_CONTACT_ID';

export const SET_TYPING_VALUE = 'SET_TYPING_VALUE';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const SAVE_MESSAGE = 'SAVE_MESSAGE';

export const CONTACT_SEARCH = 'CONTACT_SEARCH';
export const CONTACT_SEARCH_SUCCESS = 'CONTACT_SEARCH_SUCCESS';
export const CONTACT_SEARCH_FAILED = 'CONTACT_SEARCH_FAILED';
export const CONTACT_SEARCH_RESET = 'CONTACT_SEARCH_RESET';
